ALTER TABLE decisions ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE decisions ADD COLUMN IF NOT EXISTS deadline DATE;

ALTER TABLE incidents ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS deadline DATE;
